### DISCUSSION TITLE
Could not trigger deployment CI via the release event

### DISCUSSION THREAD

**Discussion by SichangHe** [release-plz/release-plz#1484] [Q&A] [answered]
Previously, we were releasing binaries (deployment) via the push event with tags. After switching to Replease-Plz, there's no tag push any more, therefore the deployment CI does not run. I referred to https://release-plz.ieni.dev/docs/extra/releasing-binaries [and added the last two lines to trigger it via releases](https://github.com/lzanini/mdbook-katex/commit/04863f5c03f9a2f46985543f68b37f02e2eb1e76):

```yml
on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]
```

But, it still does not get triggered even though Release-Plz successfully released the new version.

What did I do wrong here?
