### DISCUSSION TITLE
Changelog in commit immediately following tagged/released commit

### DISCUSSION THREAD

**Discussion by gooseops** [release-plz/release-plz#1531] [Q&A] [answered]
gm!
We are using release-plz to do what it's supposed to do.   Update changelog, tag/release for github based on crates, etc.

I used the standard config, disabled some crates in release-plz.toml, and disabled publishing of crates.

```
name: Create Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - ci/releasing


jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          manifest_path: crates/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This works, but the CHANGELOG.md files appear in the commit directly after the tagged/released commit. 

Is this expected behavior? (I would have thought the default would have included the CHANGELOG.md files in the commit that was tagged)

Is the solution to use the command `release-pr` first and then trigger `release-plz release` job when merging in a branch created by the `release-pls release-pr`?

**Comment by marcoieni** [comment]
Can you create a reproduction?
I didn't get the issue.

You can use the `update` command to see changelog changes locally

Btw the flow you described in the latest paragraph is the one that the github action uses. You can look at the source code of the action, it's simple 👍

**Comment by gooseops** [comment]
So yes it is clearly running them in the correct order, but the tagged/released commit does not contain the changelogs

```
-- Running release-plz release-pr --
  2024-06-19T20:25:48.260557Z  INFO  using release-plz config file release-plz.toml

...

-- Running release-plz release --
  2024-06-19T20:26:07.663975Z  INFO  using release-plz config file release-plz.toml
```
```
2024-06-19T20:26:07.094505Z  INFO  opened pr: https://github.com/foobarpath/pull/392
    in open_pr
    in release_pr

release_pr_output: {"prs":[{"base_branch":"ci/releasing","head_branch":"release-plz-2024-06-19T20-26-04Z","html_url":"https://github.com/foobarpath/pull/392","number":392}]}
```
Changelogs exist on that PR and commit.

However after that, the release is run and we don't see the changelogs on the tagged/released.

See this `WARN`
```
-- Running release-plz release --
  2024-06-19T20:26:07.663975Z  INFO  using release-plz config file release-plz.toml

  2024-06-19T20:26:27.585020Z  WARN  foo: failed to parse changelog at path "/home/runner/work/foobarpath/foo/CHANGELOG.md": can't read changelog file

Caused by:
    0: failed to open file `/home/runner/work/foobarpath/foo/CHANGELOG.md`
    1: No such file or directory (os error 2). The git release body will be empty.
    in release

  2024-06-19T20:26:28.664754Z  INFO  published foo 0.1.0
    in release
```
Will attempt to recreate.

**Comment by marcoieni** [comment]
Thanks, when a reproduction is ready, I'll have a look 👍

**Comment by gooseops** [comment]
Ok I've got [this repo](https://github.com/gooseops/hello_world/tree/main) as a demonstration.

In branch `ci/releasing` I've got this `main.yml` workflow:
```
name: Create Github Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - ci/releasing


jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
This `Cargo.toml`:
```
[package]
name = "goose_guessing_game"
edition = "2021"
version = "0.1.0"

[dependencies]
rand = "0.8.5"
```
This `release-plz.toml`:
```
[[package]]
name = "goose_guessing_game"
release = true
publish = false
```

The action already ran [here](https://github.com/gooseops/hello_world/actions/runs/9619204555).

The PR generated from said action and that contains the changelog is [here](https://github.com/gooseops/hello_world/pull/9).

The Release generated from said action but doesn't contain the changelog information is [here](https://github.com/gooseops/hello_world/releases/tag/v0.1.0)

The way I would expect it to work is that the Release would contain the changelog information that is in the PR, but it doesn't appear to be that way.

Please let me know what I'm missing.
