### ISSUE TITLE
Avoid bumping patch version of crates with workspace path dependencies 

### ISSUE THREAD

**Issue by jbeaurivage** [release-plz/release-plz#1852]
## Motivations

Consider a workspace with the two following crates, where `dependent` has a path dependency on `dependency`. This dependency is reexported in its public API:

```toml
[workspace]
members = ["dependent", "dependency"]
```

`dependent/Cargo.toml`
```toml
[dependencies.dependency]
version = "0.1.0"
path = "../dependency"
```

`dependent/src/lib.rs`
```rs
pub use dependent;
```

With `release_always = false`, when `release-plz` publishes a patch release for `dependency`, a new release PR is immediately created, bumping `dependent`'s dependency, and attempting to create a new release for it. 

What I would like is to avoid  making a release for `dependent`, unless the version bump in its dependency is semver-breaking.

## Additional context

This behavior is being observed in the [`atsamd-hal`](https://github.com/atsamd-rs/atsamd) project, where we have many crates which depend on one main library via path dependencies. It doesn't make sense for us to cut a release for all these support crates for every patch release (and potentially, minor release when it hits `1.0.0`) of the main crate.
