### ISSUE TITLE
Template variables support for `release-pr` branch name

### ISSUE THREAD

**Issue by AdamStrojek** [release-plz/release-plz#1991]
## Motivations

Currently we can provide static text as `pr_branch_prefix` in config file. This solution is not that flexible, and requires using suggested branch naming strategy. I think it would be better to replace it with template system that allows you on providing such configuration:

```toml
[workspace]
pr_branch_template = "release/v{{ version }}"
```

If somebody wants to remain current behavior we can leave `pr_branch_prefix` as legacy option that would automatically be interpreted as:

```toml
[workspace]
pr_branch_template = "{{ pr_branch_prefix }}-tmp-{{ date }}"
```

If instructed I can implement this feature
