### ISSUE TITLE
Ability to disable dependency updates completely

### ISSUE THREAD

**Issue by eirnym** [release-plz/release-plz#2155]
## Motivations

I have Renovate bot to care updates and I don't need to have an additional dependency updater on a side. Currently option `dependencies_update` option set to `false` surprisingly does updates and I'd like to completely suppress the action

- Would you like to implement this feature? [y/n] N

**Comment by marcoieni** [comment]
With `false` it only updates your local packages. If you don't do this before releasing, your package will be released with the older versions of your packages, especially if there are major bumps

**Comment by eirnym** [comment]
As I've wrote, renovate bot does it's work quite good and I don't want any disturbances during release process.

**Comment by marcoieni** [comment]
Let's say that you have two packages in your workspace: A and B, both at version 1.0.0.

Cargo.toml of A:

```toml
[package]
name = "A"
version = "1.0.0"

[dependencies]
B = { path = "B", version = "1" }
```

Cargo.toml of B:

```toml
[package]
name = "B"
version = "1.0.0"
```

Let's say you push one commit that introduces a breaking change in both packages. Here's how Cargo.toml of A looks like with release-plz:

```toml
[package]
name = "A"
version = "2.0.0"

[dependencies]
B = { path = "B", version = "2" }
```

If you disable local packages updates, you will have `B = { path = "B", version = "1" }`. This means that package A at version 2.0.0 will depend on an old version of package B.

renovate bot will raise a PR to update package B, and at that point release-plz will raise a PR to update to package A version `2.0.1`.

How is this better than immediately bumping the dependencies?
