### ISSUE TITLE
consolidate doc workflow example combining PR and release

### ISSUE THREAD

**Issue by nyurik** [release-plz/release-plz#2258]
The [quickstart example](https://release-plz.dev/docs/github/quickstart#3-setup-the-workflow) uses two distinct but nearly-identical jobs: `release-plz-release` and `release-plz-pr`.  Are there reasons to keep the two jobs separate?  It seems wasteful to do the same deep-cloning twice. The only differences I see are addition of `permissions.pull-requests = write` and `concurrency` settings.  It would be good to just have one  job that maybe tries to release, and if the output of the release action shows a noop, it also tries to create/update a PR.

## Ideas

I use this pattern for all my crates

```yaml
jobs:

  # The gatekeeper job - useful to identify in GitHub ruleset if merge is OK
  # This job checks if any of the previous jobs failed or were canceled.
  # This approach also allows some jobs to be skipped if they are not needed.
  ci-passed:
    needs: [ test, test-msrv ]  # <-- list of all the jobs that must succeed to consider this a pass
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

  # Release unpublished packages or create a PR with changes
  release-plz:
    needs: [ ci-passed ]  # <-- if the gatekeeper job has passed
    # runs if ci-passed and if this is a main branch push to the right repo
    if: |
      always()
      && needs.ci-passed.result == 'success'
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository_owner == 'nyurik'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io if crate's version is newer
        uses: release-plz/action@v0.5
        id: release
        with: { command: release }
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: If version is the same, create a PR proposing new version and changelog for the next release
        uses: release-plz/action@v0.5
        if: ${{ steps.release.outputs.releases_created == 'false' }}
        with: { command: release-pr }
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
```
